"""
The fixture that holds the two stemmers together.

`scripts/stem.py` computes the corpus benchmark; `src/lib/stem.ts` in the web
repo computes a reader's score against it, in their browser. The two numbers are
printed side by side, so the two stemmers have to be the same stemmer — a word
they disagree on is a difference between those numbers that nothing in either
repo would ever surface.

This writes every word both of them must agree on:

  * Porter's own published reference vocabulary, for the algorithm itself.
  * The acronyms and short tokens the MIN_STEM_LENGTH deviation exists for.
  * Real words sampled from the corpus, for the shapes English does not have
    but MCP descriptions do.

    python3 scripts/04_stem_fixture.py

Writes `data/stem_fixture.json`, and the copy in the web repo is that file. It
is committed on both sides rather than fetched, so neither test needs a network
or the other repo checked out.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from stem import stem  # noqa: E402

DATA = os.path.join(os.path.dirname(__file__), "..", "data")

#: Sampled rather than exhaustive: the point is coverage of word *shapes*, and
#: two hundred servers already exhaust the ones a stemmer can differ on.
SAMPLE_SERVERS = 200

# Porter's published reference vocabulary, trimmed to the words that exercise a
# distinct rule. Every step and every condition is represented.
REFERENCE = """
caresses ponies ties caress cats feed agreed disabled matting mating meeting
milling messing meetings plastered bled motoring sing conflated troubled sized
hopping tanned falling hissing fizzed failing filing happy sky relational
conditional rational valenci hesitanci digitizer conformabli radicalli
differentli vileli analogousli vietnamization predication operator feudalism
decisiveness hopefulness callousness formaliti sensitiviti sensibiliti
triplicate formative formalize electriciti electrical hopeful goodness revival
allowance inference airliner gyroscopic adjustable defensible irritant
replacement adjustment dependent adoption homologou communism activate
angulariti homologous effective bowdlerize probate rate cease controll roll
""".split()

# The deviation, stated as cases. Three-letter acronyms are everywhere in MCP
# schemas and Porter reads their trailing `s` as a plural.
SHORT = ["ats", "ids", "api", "apis", "url", "urls", "sql", "id", "at", "is", "a"]

# The pair the whole correction came from.
FIXTURE_PAIR = ["screens", "screening", "screen", "screened"]


def corpus_words():
    path = os.path.join(DATA, "tools.jsonl")
    if not os.path.exists(path):
        return []

    words = set()
    with open(path) as f:
        for i, line in enumerate(f):
            if i >= SAMPLE_SERVERS:
                break
            try:
                row = json.loads(line)
            except ValueError:
                continue
            for tool in row.get("tools") or []:
                text = f"{tool.get('name') or ''} {tool.get('description') or ''}"
                words.update(re.findall(r"[a-z][a-z0-9]+", text.lower()))
    return sorted(words)


def main():
    words = []
    seen = set()
    for word in FIXTURE_PAIR + REFERENCE + SHORT + corpus_words():
        if word not in seen:
            seen.add(word)
            words.append(word)

    out = {
        "note": (
            "Generated by scripts/04_stem_fixture.py in getmcpulse/mcp-schema-study. "
            "Both stemmers must reproduce every pair. Do not edit by hand."
        ),
        "min_stem_length": 4,
        "cases": {word: stem(word) for word in words},
    }

    path = os.path.join(DATA, "stem_fixture.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=1, sort_keys=False)

    print(f"{len(words)} words -> data/stem_fixture.json")
    for word in FIXTURE_PAIR:
        print(f"  {word:12} -> {out['cases'][word]}")


if __name__ == "__main__":
    main()
